prefix cpmeta: <http://meta.icos-cp.eu/ontologies/cpmeta/>
prefix prov: <http://www.w3.org/ns/prov#>
select (count (*) as ?count)
where {
	?spec cpmeta:hasDataLevel [] .
	FILTER NOT EXISTS {?spec cpmeta:hasAssociatedProject ?pro . ?pro cpmeta:hasHideFromSearchPolicy true} .
	?dobj cpmeta:hasObjectSpec ?spec .
	?dobj cpmeta:hasSizeInBytes [] .
	?dobj cpmeta:hasName ?fileName .
	?dobj cpmeta:wasSubmittedBy ?subm .
	?dobj cpmeta:wasAcquiredBy ?ac
}
