prefix cpmeta: <http://meta.icos-cp.eu/ontologies/cpmeta/>
prefix prov: <http://www.w3.org/ns/prov#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
select ?dobj
where {
	?dobj cpmeta:wasSubmittedBy ?subm .
        ?subm prov:endedAtTime ?submTime .
	FILTER NOT EXISTS {[] cpmeta:isNextVersionOf ?dobj}
}
limit 1
