prefix cpmeta: <http://meta.icos-cp.eu/ontologies/cpmeta/>
prefix terms: <http://purl.org/dc/terms/>
select ?dobj where {
	?dobj terms:hasPart ?part .
	FILTER NOT EXISTS {[] cpmeta:isNextVersionOf ?dobj}
}
limit 10
