prefix cpmeta: <http://meta.icos-cp.eu/ontologies/cpmeta/>
prefix prov: <http://www.w3.org/ns/prov#>
select * where {
  ?dobj cpmeta:wasSubmittedBy/prov:endedAtTime ?submTime .
}
order by ?submTime
offset 0 limit 5
